drop table bike if exists
create table bike (
id bigint generated by default as identity,
name varchar(50),
email varchar(50),
phone varchar(15),
model varchar(15),
serial_number varchar(15),
purchase_date date,
purchase_price decimal,
contact boolean not null
primary key (id))